development: &default
  adapter: sqlite3
  database: Gitlab-project_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: Gitlab-project_test
